### ISSUE TITLE
Can't add new items in calendar

### ISSUE THREAD

**Issue by eitch** [traggo/server#187]
When i click on the calendar, i can't add anything. This is new in 0.5.0. Previously i could click in the calendar and it would open a window where i can add items.

Existing items open, and i can edit them just fine.

A new change, which i find unwelcome: The "Show Notes" function might be nice for some, but i always add a note and now i need to click another button to enter text.

**Comment by eitch** [comment]
Sorry, that was me being stupid. Drag and drop =)

**Comment by eitch** [comment]
But the issue with the show notes is still there =)

**Comment by eitch** [comment]
Yes, but like i said, i add notes to every entry and now i need to click additionally. A small issue, i know, but still =)

**Comment by jmattheis** [comment]
Hmm understood, we can probably bring this back in desktop resolutions, or maybe we could add another setting for having the notes expanded by default, so you'd need zero clicks.

**Comment by eitch** [comment]
Hi @jmattheis could you perhaps implement, that the notes be expanded by default on desktop resolutions?

On a side note, i would try and send a PR, but i can't get the dev environment to work as is described here: https://traggo.net/dev/setup/

I performed the following commands:
```
git clone https://github.com/traggo/server.git && cd server
make download-tools
make install
make generate
```

and then generate errors out with:
```
❯ make generate
gqlgen
make: gqlgen: No such file or directory
make: *** [Makefile:18: generate-go] Error 127

server on  master via  v1.23.2 
🔴 2 ❯ gqlgen
gqlgen: command not found
```

So, as i am not a go developer, could you extend your docs to handle this situation, that would be great. I'm running on an Ubuntu based system.

**Comment by b1tray3r** [comment]
> Hmm understood, we can probably bring this back in desktop resolutions, or maybe we could add another setting for having the notes expanded by default, so you'd need zero clicks.

Yes! Please! 100%

**Comment by jmattheis** [comment]
@eitch, you need the go binary directory on your `$PATH`. E.g. `export PATH="$PATH:$(go env GOPATH)/bin"`

**Comment by eitch** [comment]
Now i'm on a different system and get the following when doing `make install`:

```
❯ make install
go mod download
(cd ui && yarn)
/bin/sh: 1: yarn: not found
make: *** [Makefile:55: install-js] Error 127
```

But `make download-tools` worked... Is there a prerequisite i need to do before installing anything?

**Comment by jmattheis** [comment]
You need to have yarn, node, and go installed on your system.

**Comment by eitch** [comment]
I used nvm, with which i installed node 11.x, this lead to problems with yarn:

```
/home/eitch/.nvm/versions/node/v11.15.0/lib/node_modules/corepack/dist/yarn.js:2
process.env.COREPACK_ENABLE_DOWNLOAD_PROMPT??='1'
                                            ^

SyntaxError: Unexpected token ?
    at Module._compile (internal/modules/cjs/loader.js:760:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
    at internal/main/run_main_module.js:21:11
```

After upgrading to Node 16, i was able to get a step further and download the tools and run install, but generate still fails, this time it seems to be a go compile error:

```
❯ make generate
gqlgen
go: downloading github.com/andreyvit/diff v0.0.0-20170406064948-c7f18ee00883
go: downloading github.com/PuerkitoBio/goquery v1.9.3
go: downloading gopkg.in/yaml.v2 v2.4.0
go: downloading github.com/arbovm/levenshtein v0.0.0-20160628152529-48b4e1c0c4d0
go: downloading github.com/dgryski/trifles v0.0.0-20200323201526-dd97f9abfb48
go: downloading gopkg.in/check.v1 v0.0.0-20161208181325-20d25e280405
go: downloading github.com/sergi/go-diff v1.3.1
go: downloading github.com/andybalholm/cascadia v1.3.2
go: downloading golang.org/x/net v0.29.0
validation failed: packages.Load: /home/eitch/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.1.linux-amd64/src/slices/iter.go:50:17: cannot range over seq (variable of type iter.Seq[E])
/home/eitch/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.1.linux-amd64/src/maps/iter.go:51:20: cannot range over seq (variable of type iter.Seq2[K, V])

make: *** [Makefile:18: generate-go] Error 1
```

**Comment by jmattheis** [comment]
use latest versions for yarn, go, node.
