### ISSUE TITLE
Deletion of admin user causes crashing

### ISSUE THREAD

**Issue by basp0** [traggo/server#93]
**Describe the bug**
When the default admin user is deleted, even if another admin user exists, the application crashes.
**To Reproduce**
1. Start a fresh instance of Traggo.
2. Delete the default admin user.
3. The website should now be unresponsive.

**Expected behavior**
Either the default admin shouldn't be delete-able, or this error should not take place.
If an admin user exists, other admins must be removable, if not, there should be an error message stating the same.

**Screenshots**
Not applicable
 
**Additional context**
I have not modified the config files at all, and i'm not using Nginx.
This is what I get whenever I visit the website:
```
2021-05-12T14:39:58+05:30 PNC User not found deviceID=1 userID=1
2021/05/12 14:39:58 http: panic serving 127.0.0.1:50246: User not found
goroutine 132 [running]:
net/http.(*conn).serve.func1(0xc0000b6e60)
	/usr/local/go/src/net/http/server.go:1767 +0x139
panic(0xb9ffe0, 0xc000099fa0)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/rs/zerolog.(*Logger).Panic.func1(0xca6cac, 0xe)
	/go/pkg/mod/github.com/rs/zerolog@v1.11.0/log.go:307 +0x4f
github.com/rs/zerolog.(*Event).msg(0xc0002a1810, 0xca6cac, 0xe)
	/go/pkg/mod/github.com/rs/zerolog@v1.11.0/event.go:146 +0x1e6
github.com/rs/zerolog.(*Event).Msg(...)
	/go/pkg/mod/github.com/rs/zerolog@v1.11.0/event.go:110
github.com/traggo/server/auth.reqisterUser(0xc000023100, 0xf63020, 0xc000312460, 0xc0002b60b0, 0xc0002aec80)
	/proj/auth/middleware.go:63 +0x862
github.com/traggo/server/auth.Middleware.func1.1(0xf63020, 0xc000312460, 0xc000023100)
	/proj/auth/middleware.go:30 +0x5e
net/http.HandlerFunc.ServeHTTP(0xc0004d72a0, 0xf63020, 0xc000312460, 0xc000023100)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0002ca180, 0xf63020, 0xc000312460, 0xc000022f00)
	/go/pkg/mod/github.com/gorilla/mux@v1.7.2/mux.go:212 +0xe2
net/http.serverHandler.ServeHTTP(0xc000312000, 0xf63020, 0xc000312460, 0xc000022f00)
	/usr/local/go/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc0000b6e60, 0xf649a0, 0xc000286000)
	/usr/local/go/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2927 +0x38e

```

**Comment by jmattheis** [comment]
Hey could you execute the following command with your database file?
```
$ sqlite3 yoursqlitedatabase.db ".schema devices"
```
Do you know with which traggo version you initialized the database

I could reproduce the problem with an old database file, but not with a newly created one.

**Comment by tcuc** [comment]
I have done this, without the site crashing. 
i messed up some variables while deploying the app on docker, and the default user was set to [null], i then created the user i wanted, and deleted the default admin user [null], and Traggo still works fine.
